/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/fishbot.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cone.geometry}
        material={materials['Material.001']}
        position={[-0.03, -0.05, 0.33]}
        rotation={[0, -1.18, Math.PI / 2]}
        scale={0.2}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-0.16, -1.3, 0.12]}
        scale={[0.91, 0.42, 0.91]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-0.16, -1.57, 0.12]}
        scale={[0.4, 0.18, 0.4]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[0.79, -1.1, -0.03]}
        rotation={[0, 0, 0.5]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[0.79, -1.1, -0.03]}
        rotation={[0, 0, 0.5]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials['Material.011']}
        position={[0.79, -1.1, -0.03]}
        rotation={[0, 0, 0.5]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[1.34, -2.55, -0.03]}
        rotation={[0, 0, 0.5]}
        scale={[0.28, 0.28, 0.4]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[1.42, -2.75, -0.03]}
        rotation={[0, 0, 0.5]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={materials['Material.005']}
        position={[-0.17, -0.05, 0]}
        rotation={[0, -1.18, 0]}
        scale={0.25}
      />
      <mesh
        geometry={nodes.Cube028.geometry}
        material={materials['Material.003']}
        position={[-0.16, 0.01, -0.33]}
        rotation={[0.34, -0.38, 0.31]}
        scale={[0.06, 0.06, 0.06]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials['Material.010']}
        position={[-0.22, 0.27, -0.12]}
        scale={[0.11, 0.09, 0.11]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials['Material.012']}
        position={[-0.18, 1.92, 0.13]}
        scale={[0.53, 0.44, 0.53]}
      />
      <mesh
        geometry={nodes.NurbsPath.geometry}
        material={materials['Material.014']}
        position={[0.33, -0.2, 0.09]}
        rotation={[0, -0.36, 0]}
        scale={0.65}
      />
      <mesh
        geometry={nodes.NurbsPath001.geometry}
        material={materials['Material.013']}
        position={[0.27, -0.2, 0.22]}
        rotation={[0, -0.55, 0]}
        scale={0.65}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials['Material.004']}
        position={[-0.16, 0.21, 0.12]}
        scale={1.4}
      />
      <mesh
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        position={[-0.16, -1.7, 0.12]}
        scale={0.22}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={nodes.Torus001.material}
        position={[-0.16, -1.88, 0.12]}
        scale={0.17}
      />
      <mesh
        geometry={nodes.Torus002.geometry}
        material={nodes.Torus002.material}
        position={[-0.16, -2.03, 0.12]}
        scale={0.12}
      />
    </group>
  )
}

useGLTF.preload('/fishbot.gltf')
