/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/plants.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.PLANTS_ON_TABLE_10K_1.geometry} material={materials.desk_top} />
        <mesh geometry={nodes.PLANTS_ON_TABLE_10K_2.geometry} material={materials.caps} />
        <mesh geometry={nodes.PLANTS_ON_TABLE_10K_3.geometry} material={materials.legs} />
        <mesh geometry={nodes.PLANTS_ON_TABLE_10K_4.geometry} material={materials._auto_} />
      </group>
    </group>
  )
}

useGLTF.preload('/plants.gltf')
