/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/toaster.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0.28]} rotation={[Math.PI / 2, 0, 3.12]} scale={0.2}>
        <mesh geometry={nodes.Cylinder019.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder019_1.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cylinder019_2.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Cylinder019_3.geometry} material={materials['Material.017']} />
        <mesh geometry={nodes.Cylinder019_4.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder019_5.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cylinder019_6.geometry} material={materials['Material.020']} />
      </group>
    </group>
  )
}

useGLTF.preload('/toaster.gltf')
